import { TANK_CAP } from './constants.js';

export const DEF = {
  belt: {
    n: 'Förderband',
    g: '»',
    col: '#444',
    cat: 'halle',
    band: 'belt',
    w: 1,
    h: 0,
    cost: 20,
    e: 0.05,
    dirt: 0.35,
    d: 'Transportiert Sticks und Leichen nach rechts.',
  },
  spike: {
    n: 'Spikes-Walze',
    g: '✹',
    col: '#8a2a24',
    cat: 'halle',
    band: 'over',
    w: 2,
    h: 120,
    cost: 160,
    e: 0.4,
    dirt: 0.55,
    kill: 'contact',
    dmg: 'sever',
    d: 'Reißt Gliedmaßen ab. Verwundete verbluten auf dem Band.',
  },
  press: {
    n: 'Presse',
    g: '▤',
    col: '#6a3a30',
    cat: 'halle',
    band: 'over',
    w: 2,
    h: 120,
    cost: 280,
    e: 0.6,
    dirt: 0.45,
    kill: 'timed',
    dmg: 'crush',
    d: 'Quetscht im Takt. Muss über Band stehen.',
  },
  schleuder: {
    n: 'Abschleuderer',
    g: '☄',
    col: '#7a4a24',
    cat: 'halle',
    band: 'over',
    w: 2,
    h: 120,
    cost: 240,
    e: 0.5,
    dirt: 0.5,
    kill: 'eject',
    d: 'Schleudert sitzende Sticks mitsamt Stuhl dynamisch in den Keller.',
  },
  spawn: {
    n: 'Eingang',
    g: '▶',
    col: '#555',
    cat: 'halle',
    band: 'over',
    w: 3,
    h: 110,
    cost: 0,
    e: 0,
    max: 1,
    d: 'Setzt frische Stühle aufs Band. Sticks fahren permanent sitzend mit.',
  },
  drain: {
    n: 'Abfluss',
    g: '≋',
    col: '#555',
    cat: 'keller',
    band: 'keller',
    w: 1,
    h: 62,
    cost: 110,
    e: 0.15,
    d: 'Pumpt Blut vom Kellerboden in die Tanks.',
  },
  bin: {
    n: 'Container',
    g: '▥',
    col: '#4a4a4a',
    cat: 'keller',
    band: 'keller',
    w: 3,
    h: 172,
    cost: 220,
    e: 0.1,
    cap: 9,
    d: 'Fängt Leichen. Sie verrotten zu Blut und Asche.',
  },
  oven: {
    n: 'Verbrenner',
    g: '♨',
    col: '#7a3524',
    cat: 'keller',
    band: 'keller',
    w: 2,
    h: 142,
    cost: 380,
    e: 0.8,
    cap: 3,
    d: 'Verbrennt Leichen: +Energie, +Asche.',
  },
  acid: {
    n: 'Säurebad',
    g: '☣',
    col: '#3f4a3a',
    cat: 'keller',
    band: 'keller',
    w: 2,
    h: 112,
    cost: 460,
    e: 0.5,
    cap: 3,
    d: 'Löst Leichen auf: +Geld.',
  },
  tank: {
    n: 'Bluttank',
    g: '▮',
    col: '#4a4a4a',
    cat: 'keller',
    band: 'keller',
    w: 2,
    h: 150,
    cost: 190,
    e: 0,
    d: '+' + TANK_CAP + ' Blutkapazität.',
  },
  market: {
    n: 'Blutmarkt',
    g: '€',
    col: '#555',
    cat: 'oben',
    band: 'oben',
    w: 2,
    h: 112,
    cost: 320,
    e: 0.3,
    d: 'Verkauft Blut gegen Geld (1,4 €/Blut).',
  },
  gen: {
    n: 'Generator',
    g: '⚡',
    col: '#555',
    cat: 'oben',
    band: 'oben',
    w: 2,
    h: 112,
    cost: 340,
    e: 0,
    d: 'Wandelt Blut in Energie (8 Blut/s → 15 E/s).',
  },
  lab: {
    n: 'Reinraum',
    g: '✚',
    col: '#4a5560',
    cat: 'oben',
    band: 'oben',
    w: 2,
    h: 112,
    cost: 280,
    e: 0.4,
    d: 'Reinigt alle Maschinen automatisch.',
  },
};
export const CATS = [
  ['halle', 'Halle'],
  ['keller', 'Keller'],
  ['oben', 'Oben'],
];
export const BAND_LABEL = { belt: 'Band', over: 'Über Band', keller: 'Keller', oben: 'Oben' };
