import {
  ACID_CAP,
  OVEN_CAP,
  ROUTE_CAP,
  SHOP_CAP,
  TANK_CAP,
  BIN_CAP,
} from './constants.js';

/**
 * Gebäudedefinitionen für die freie Rasterwelt.
 *
 * Ports sind **relative** Richtungen zur Baurichtung `b.dir`:
 *   0 = vorwärts, +1 = im Uhrzeigersinn, -1 = dagegen.
 * `sink` nimmt Waren von jeder Seite an, `pass` transportiert Waren
 * einfach hindurch, `route` legt Waren kurz ab und schickt sie weiter.
 */
export const DEF = {
  belt: {
    n: 'Förderband',
    icon: 'belt',
    col: '#444',
    cat: 'band',
    kind: 'belt',
    w: 1,
    h: 1,
    cost: 20,
    e: 0.02,
    dirt: 0.35,
    d: 'Zieh eine Strecke: erst auf den Start klicken, dann auf das Ende.',
  },
  spawn: {
    n: 'Eingang',
    icon: 'spawn',
    col: '#555',
    cat: 'masch',
    kind: 'src',
    w: 2,
    h: 1,
    cost: 0,
    e: 0,
    out: [0],
    d: 'Setzt frische Sticks aufs Band – braucht ein Band am Ausgang.',
  },
  spike: {
    n: 'Spikes-Walze',
    icon: 'spike',
    col: '#8a2a24',
    cat: 'masch',
    kind: 'pass',
    w: 3,
    h: 2,
    cost: 160,
    e: 0.4,
    dirt: 0.55,
    cut: 'sever',
    in: [0],
    out: [0],
    d: 'Reißt zufällig Gliedmaßen ab. Zielwahl im Inspektor.',
  },
  press: {
    n: 'Presse',
    icon: 'press',
    col: '#6a3a30',
    cat: 'masch',
    kind: 'pass',
    w: 2,
    h: 3,
    cost: 280,
    e: 0.6,
    dirt: 0.45,
    cut: 'crush',
    in: [0],
    out: [0],
    d: 'Hält Waren fest und quetscht sie im Takt zu Brei.',
  },
  blade: {
    n: 'Presse mit Klingen',
    icon: 'blade',
    col: '#7a2a3a',
    cat: 'masch',
    kind: 'pass',
    w: 3,
    h: 3,
    cost: 320,
    e: 0.55,
    dirt: 0.5,
    cut: 'sever',
    targeted: true,
    in: [0],
    out: [0],
    unlock: 'prec_blade',
    d: 'Trennt das eingestellte Zielkörperteil präzise ab.',
  },
  schleuder: {
    n: 'Abschleuderer',
    icon: 'schleuder',
    col: '#7a4a24',
    cat: 'masch',
    kind: 'pass',
    w: 4,
    h: 2,
    cost: 240,
    e: 0.5,
    dirt: 0.5,
    cut: 'eject',
    in: [0],
    out: [0],
    d: 'Schleudert Waren vom Band – sie fallen nach unten.',
  },
  bin: {
    n: 'Container',
    icon: 'bin',
    col: '#4a4a4a',
    cat: 'masch',
    kind: 'sink',
    w: 2,
    h: 1,
    cost: 220,
    e: 0.1,
    cap: BIN_CAP,
    d: 'Fängt Waren. Sie verrotten zu Blut und Asche.',
  },
  oven: {
    n: 'Verbrenner',
    icon: 'oven',
    col: '#7a3524',
    cat: 'masch',
    kind: 'sink',
    w: 3,
    h: 3,
    cost: 380,
    e: 0.8,
    cap: OVEN_CAP,
    process: 'burn',
    d: 'Verbrennt Waren: +Energie, +Asche.',
  },
  acid: {
    n: 'Säurebad',
    icon: 'acid',
    col: '#3f4a3a',
    cat: 'masch',
    kind: 'sink',
    w: 4,
    h: 2,
    cost: 460,
    e: 0.5,
    cap: ACID_CAP,
    process: 'dissolve',
    d: 'Löst Waren auf: +Geld.',
  },
  shop: {
    n: 'Verkauf',
    icon: 'shop',
    col: '#2f6a4a',
    cat: 'hand',
    kind: 'sink',
    w: 3,
    h: 2,
    cost: 260,
    e: 0.2,
    cap: SHOP_CAP,
    process: 'sell',
    unlock: 'eco_shop',
    d: 'Nimmt Körperteile über Bänder an und verkauft sie.',
  },
  lab: {
    n: 'Reinraum',
    icon: 'lab',
    col: '#4a5560',
    cat: 'masch',
    kind: 'clean',
    w: 2,
    h: 1,
    cost: 280,
    e: 0.4,
    d: 'Reinigt alle Maschinen automatisch.',
  },
  weiche: {
    n: 'Weiche',
    icon: 'weiche',
    col: '#4a5a7a',
    cat: 'logi',
    kind: 'route',
    w: 1,
    h: 1,
    cost: 120,
    e: 0.1,
    cap: ROUTE_CAP,
    in: [0],
    out: [0, 1],
    d: 'Teilt den Fluss: Waren wechseln ab zwischen beiden Ausgängen.',
  },
  merge: {
    n: 'Zusammenführung',
    icon: 'merge',
    col: '#4a5a7a',
    cat: 'logi',
    kind: 'route',
    w: 1,
    h: 1,
    cost: 140,
    e: 0.1,
    cap: ROUTE_CAP,
    in: [0, -1],
    out: [0],
    d: 'Führt zwei Bänder zu einem zusammen.',
  },
  filter: {
    n: 'Filter',
    icon: 'filter',
    col: '#5a4a7a',
    cat: 'logi',
    kind: 'route',
    w: 1,
    h: 1,
    cost: 200,
    e: 0.15,
    cap: ROUTE_CAP,
    in: [0],
    out: [0, 1],
    unlock: 'log_filter',
    d: 'Sortiert nach Körperteil oder Zustand – Regel im Inspektor.',
  },
  pipe: {
    n: 'Blut-Pipe',
    icon: 'pipe',
    col: '#7a3030',
    cat: 'rohr',
    kind: 'pipe',
    w: 1,
    h: 1,
    cost: 12,
    e: 0,
    dirt: 0.05,
    d: 'Verbindet Absaugungen, Tanks, Markt und Generator zu einem Netz.',
  },
  tank: {
    n: 'Bluttank',
    icon: 'tank',
    col: '#4a4a4a',
    cat: 'rohr',
    kind: 'tank',
    w: 2,
    h: 4,
    cost: 190,
    e: 0,
    d: '+' + TANK_CAP + ' Blutkapazität, auch per Pipe anschlussfähig.',
  },
  drain: {
    n: 'Abfluss',
    icon: 'drain',
    col: '#555',
    cat: 'rohr',
    kind: 'drain',
    w: 1,
    h: 1,
    cost: 110,
    e: 0.15,
    d: 'Saugt Bodenblut auf und pumpt es in Tank oder Pipe-Netz.',
  },
  market: {
    n: 'Blutmarkt',
    icon: 'market',
    col: '#555',
    cat: 'hand',
    kind: 'market',
    w: 3,
    h: 3,
    cost: 320,
    e: 0.3,
    d: 'Verkauft Blut (1,4 €/Blut) – mit Reserve im Inspektor.',
  },
  gen: {
    n: 'Generator',
    icon: 'gen',
    col: '#555',
    cat: 'hand',
    kind: 'gen',
    w: 3,
    h: 2,
    cost: 340,
    e: 0,
    d: 'Wandelt Blut in Energie (8 Blut/s → 15 E/s).',
  },
};

export const CATS = [
  ['band', 'Bänder'],
  ['masch', 'Maschinen'],
  ['logi', 'Logistik'],
  ['rohr', 'Rohre'],
  ['hand', 'Handel'],
];
