/**
 * Skill-Tree als reine Daten. Knoten lassen sich ohne Codeänderung ergänzen:
 * ein neuer Eintrag mit `br`, `cur`, `costs`, optional `req`, `fx` und `unlock`
 * genügt – `core/skill.js` wertet die Daten generisch aus.
 *
 * Währungen: `blood` (aus den Bluttanks) oder `parts` (Körperteil-Vorrat).
 * `fx` wirkt sofort, auch auf bereits gebaute Maschinen:
 *   mul = Multiplikator (wird multipliziert), add = Zuschlag (wird addiert).
 */
export const BRANCHES = [
  { id: 'prec', n: 'Präzision', cur: 'blood', d: 'Gezieltes Abtrennen und Trefferquote.' },
  { id: 'mach', n: 'Maschinen', cur: 'parts', d: 'Tempo, Schaden, Sauberkeit, Energie.' },
  { id: 'blo', n: 'Blut & Pipes', cur: 'parts', d: 'Durchfluss, Kapazität, weniger Verlust.' },
  { id: 'log', n: 'Logistik', cur: 'parts', d: 'Bänder, Weichen und Filter.' },
  { id: 'eco', n: 'Wirtschaft', cur: 'parts', d: 'Preise, Baukosten, Reinigung.' },
  { id: 'ene', n: 'Energie', cur: 'parts', d: 'Generator und Verbrenner.' },
];

export const SKILL = [
  /* ------------------------------ Präzision (Blut) ------------------------------ */
  {
    id: 'prec_aim',
    br: 'prec',
    n: 'Fokus',
    d: 'Trefferquote beim gezielten Abtrennen +12 Prozentpunkte.',
    cur: 'blood',
    max: 3,
    costs: [40, 90, 180],
    req: [],
    fx: [{ k: 'hit', add: 0.12 }],
  },
  {
    id: 'prec_blade',
    br: 'prec',
    n: 'Klingenpresse',
    d: 'Schaltet die Presse mit Klingen frei und verbessert die Trefferquote.',
    cur: 'blood',
    max: 1,
    costs: [120],
    req: [['prec_aim', 1]],
    fx: [{ k: 'hit', add: 0.08 }],
    unlock: ['blade'],
  },
  {
    id: 'prec_micro',
    br: 'prec',
    n: 'Mikroschnitt',
    d: 'Trefferquote +15 Prozentpunkte.',
    cur: 'blood',
    max: 2,
    costs: [160, 320],
    req: [['prec_blade', 1]],
    fx: [{ k: 'hit', add: 0.15 }],
  },
  {
    id: 'prec_multi',
    br: 'prec',
    n: 'Doppelgriff',
    d: 'Die Maschine trifft pro Durchgang ein weiteres Körperteil.',
    cur: 'blood',
    max: 2,
    costs: [220, 440],
    req: [['prec_aim', 3]],
    fx: [{ k: 'multi', add: 1 }],
  },

  /* ------------------------------ Maschinen ------------------------------ */
  {
    id: 'mach_speed',
    br: 'mach',
    n: 'Überdrehung',
    d: 'Klingen, Presse und Walze laufen 8 % schneller.',
    cur: 'parts',
    max: 3,
    costs: [25, 50, 90],
    req: [],
    fx: [{ k: 'machSpeed', mul: 1.08 }],
  },
  {
    id: 'mach_dmg',
    br: 'mach',
    n: 'Härtere Klingen',
    d: 'Schaden der Klingen, Presse und Walze +12 %.',
    cur: 'parts',
    max: 3,
    costs: [30, 60, 120],
    req: [['mach_speed', 1]],
    fx: [{ k: 'machDmg', mul: 1.12 }],
  },
  {
    id: 'mach_dirt',
    br: 'mach',
    n: 'Schmutzabwehr',
    d: 'Verschmutzung der Maschinen −10 % pro Stufe.',
    cur: 'parts',
    max: 3,
    costs: [20, 40, 80],
    req: [],
    fx: [{ k: 'machDirt', mul: 0.9 }],
  },
  {
    id: 'mach_power',
    br: 'mach',
    n: 'Energiesparung',
    d: 'Energiebedarf der Maschinen −8 % pro Stufe.',
    cur: 'parts',
    max: 3,
    costs: [25, 50, 100],
    req: [['mach_speed', 2]],
    fx: [{ k: 'machEnergy', mul: 0.92 }],
  },

  /* ------------------------------ Blut & Pipes ------------------------------ */
  {
    id: 'blo_flow',
    br: 'blo',
    n: 'Höherer Durchfluss',
    d: 'Blutdurchfluss der Pipe-Netze +15 % pro Stufe.',
    cur: 'parts',
    max: 3,
    costs: [30, 60, 120],
    req: [],
    fx: [{ k: 'pipeFlow', mul: 1.15 }],
  },
  {
    id: 'blo_cap',
    br: 'blo',
    n: 'Große Tanks',
    d: '+50 Blutkapazität je Tank und Stufe.',
    cur: 'parts',
    max: 3,
    costs: [35, 70, 140],
    req: [['blo_flow', 1]],
    fx: [{ k: 'tankCap', add: 50 }],
  },
  {
    id: 'blo_seal',
    br: 'blo',
    n: 'Dichte Leitungen',
    d: 'Verlust beim Einspeisen ins Netz −40 % pro Stufe.',
    cur: 'parts',
    max: 2,
    costs: [45, 90],
    req: [['blo_cap', 1]],
    fx: [{ k: 'pipeLoss', mul: 0.6 }],
  },

  /* ------------------------------ Logistik ------------------------------ */
  {
    id: 'log_speed',
    br: 'log',
    n: 'Bandantrieb',
    d: 'Bandgeschwindigkeit +8 % pro Stufe.',
    cur: 'parts',
    max: 3,
    costs: [25, 50, 100],
    req: [],
    fx: [{ k: 'beltSpeed', mul: 1.08 }],
  },
  {
    id: 'log_route',
    br: 'log',
    n: 'Mehr Platz',
    d: 'Weichen, Zusammenführung und Filter fassen +2 Waren.',
    cur: 'parts',
    max: 3,
    costs: [30, 60, 120],
    req: [['log_speed', 1]],
    fx: [{ k: 'routeCap', add: 2 }],
  },
  {
    id: 'log_filter',
    br: 'log',
    n: 'Sortierer',
    d: 'Schaltet den Filter frei.',
    cur: 'parts',
    max: 1,
    costs: [60],
    req: [['log_route', 1]],
    fx: [],
    unlock: ['filter'],
  },

  /* ------------------------------ Wirtschaft ------------------------------ */
  {
    id: 'eco_price',
    br: 'eco',
    n: 'Marktkenntnis',
    d: 'Verkaufspreise für Blut und Körperteile +8 % pro Stufe.',
    cur: 'parts',
    max: 3,
    costs: [30, 65, 130],
    req: [],
    fx: [{ k: 'price', mul: 1.08 }],
  },
  {
    id: 'eco_build',
    br: 'eco',
    n: 'Günstig bauen',
    d: 'Baukosten −6 % pro Stufe.',
    cur: 'parts',
    max: 3,
    costs: [25, 50, 100],
    req: [['eco_price', 1]],
    fx: [{ k: 'buildCost', mul: 0.94 }],
  },
  {
    id: 'eco_clean',
    br: 'eco',
    n: 'Günstig reinigen',
    d: 'Reinigungskosten −10 % pro Stufe.',
    cur: 'parts',
    max: 2,
    costs: [30, 60],
    req: [['eco_build', 1]],
    fx: [{ k: 'cleanCost', mul: 0.9 }],
  },
  {
    id: 'eco_shop',
    br: 'eco',
    n: 'Verkaufsstelle',
    d: 'Schaltet die Verkaufsannahme frei.',
    cur: 'parts',
    max: 1,
    costs: [50],
    req: [['eco_price', 2]],
    fx: [],
    unlock: ['shop'],
  },

  /* ------------------------------ Energie ------------------------------ */
  {
    id: 'ene_gen',
    br: 'ene',
    n: 'Heißere Verbrennung',
    d: 'Energieertrag des Generators +10 % pro Stufe.',
    cur: 'parts',
    max: 3,
    costs: [35, 70, 140],
    req: [],
    fx: [{ k: 'gen', mul: 1.1 }],
  },
  {
    id: 'ene_oven',
    br: 'ene',
    n: 'Heißere Öfen',
    d: 'Energie aus dem Verbrenner +15 % pro Stufe.',
    cur: 'parts',
    max: 3,
    costs: [30, 60, 120],
    req: [['ene_gen', 1]],
    fx: [{ k: 'oven', mul: 1.15 }],
  },
];

/** Startvorrat am Ende des Tutorials, damit der erste Knoten kauftbar ist. */
export const TUTORIAL_GIFT = {
  blood: 80,
  parts: { head: 2, torso: 4, armL: 6, armR: 6, legL: 4, legR: 4 },
};
